export const clientLogos = [
  { src: "/images/logos/Instituto_di_Moda_Burgo.webp", alt: "Instituto di Moda Burgo" },
  { src: "/images/logos/JF_Ambiental.webp", alt: "JF Ambiental" },
  { src: "/images/logos/Kenco_Saude.webp", alt: "Kenco Saúde" },
  { src: "/images/logos/Maira_Cardi.webp", alt: "Maíra Cardi" },
  { src: "/images/logos/MapleBear.webp", alt: "MapleBear" },
  { src: "/images/logos/Mari_Tortella.webp", alt: "Mari Tortella" },
  { src: "/images/logos/Mottainai_Brasil.webp", alt: "Mottainai Brasil" },
  { src: "/images/logos/Recicle_Ambiental.webp", alt: "Recicle Ambiental" },
  { src: "/images/logos/Seca_Voce.webp", alt: "Seca Você" },
  { src: "/images/logos/Tasso_Lago.webp", alt: "Tasso Lago" },
  { src: "/images/logos/Centro_Odontologico_Filhote.webp", alt: "Centro Odontológico Filhote" },
  { src: "/images/logos/Cura_Voce.webp", alt: "Cura Você" },
  { src: "/images/logos/Dani_Uchoa.webp", alt: "Dani Uchoa" },
  { src: "/images/logos/Desafio_Seca.webp", alt: "Desafio Seca" },
  { src: "/images/logos/Financial_Move.webp", alt: "Financial Move" },
  { src: "/images/logos/Fluency_Academy.webp", alt: "Fluency Academy" },
  { src: "/images/logos/HalterTech.webp", alt: "HalterTech" },
];
